- hosts: servers
  remote_user: root
  roles:
    - { role: micropyramid.django, project_name: 'your_project_name', database: 'mysql or postgresql or empty', os_release: 12.04_or_14.04_or_15.04 }
    - { role: micropyramid.uwsgi_django_setup, project_name: 'your_project_name' }
    - { role: micropyramid.nginx_django_setup, project_name: "your_project_name", server_name: "domain_name_or_ip_addr", server_port: "port_number" }

