- name: Creates directory
  file: "path=/home/{{project_name}} state=directory"

- name: create virtualenv and install django in it
  pip: "name=django virtualenv=/home/{{project_name}}/env virtualenv_command=virtualenv"

- name: install a django project
  command: "/home/{{project_name}}/env/bin/django-admin.py startproject {{project_name}} chdir=/home/{{project_name}}/"
