---
- name: Install required apt-packages
  apt: "name='{{ item }}' state=present force=yes"

  with_items:
    - python-dev
    - python-virtualenv
    - python-pip
    - openjdk-7-jre-headless
    - libtiff5-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.6-dev
    - tk8.6-dev
    - python-tk
    - redis-server
    - git
    - ruby

#- name: Create UWSGI vassals directory
#  file: "path={{vassals_dir}}  state=directory"
#
#- name: setup uwsgi in supervisor
#  template: "src=uwsgi-server.j2 dest={{supervisor_conf_dir}}/uwsgi-runner.conf"
#
#- name: update supervisor
#  supervisorctl: name=uwsgi-runner state=restarted
